"""Added img_url field in table

Revision ID: 57a5d9402351
Revises: 0fcb7a55135c
Create Date: 2024-11-15 14:20:34.025225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a5d9402351'
down_revision = '0fcb7a55135c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('province_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('province_items', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
